### ISSUE TITLE
Hiding title bar when clicking PR from list

### ISSUE THREAD

**Issue by salbahra** [Mimeo/VSTSExtension-ActivePullRequests#14]
The first time a pull request link is clicked from the list, the title bar is hidden and no action occurs. The issue exists when a long list of pull requests are pending (larger than the viewable screen area). I have been able to reproduce this issue on devices with small screens or using a smaller desktop browser window.

The issue seems to be a CSS one where the body of the `iframe` generated by `hub.html` is 20px up causing the `hub-title` to be hidden and for links to be invalid (hit area gets moved as soon you click). I haven't found the exact cause for this yet or I would have submitted a PR but wanted to document the issue here.

**Comment by nshenoy** [comment]
Excellent! Thanks for fixing this. Much appreciated.
