### ISSUE TITLE
Sorting for "Created By" Column Does Nothing

### ISSUE THREAD

**Issue by GuacoIV** [Mimeo/VSTSExtension-ActivePullRequests#15]
When I click the "Created By" column header on the All Active Pull Requests page, the order of the entries does not change.

**Comment by nshenoy** [comment]
There is a fix pending for this issue. We'll be posting an update to the marketplace pretty soon. Thanks for your patience!

**Comment by GuacoIV** [comment]
Thanks for the update!

**Comment by nshenoy** [comment]
This has been fixed! The extension has been published under a new Mimeo publisher, with the previous one marked as "deprecated." Please uninstall the old extension and install the new one from here: https://marketplace.visualstudio.com/items?itemName=mimeo-vs-marketplace.mimeo-active-pull-requests . Thanks!
