### ISSUE TITLE
No Scroll Bar

### ISSUE THREAD

**Issue by GuacoIV** [Mimeo/VSTSExtension-ActivePullRequests#21]
We currently have 78 pull requests open, which does not fit in the page without a scroll bar.  There is no scrollbar available, so our only option to see the others is to zoom out or use the dev console to add the "overflow: scroll" styling.

**Comment by sand-head** [comment]
was able to reproduce, this is another instance of Microsoft's VSS SDK applying strange, unnecessary styling to the extension. in this case, it's preapplying `overflow: hidden` to the `body` tag. I'll submit a PR overwriting that with `overflow: auto` soon

**Comment by nshenoy** [comment]
@GuacoIV version 1.0.2 was just published. Could you see if the extension shows all of your PRs? Thanks!

**Comment by GuacoIV** [comment]
@nshenoy Can see them all now - confirmed.  Thanks!
