### ISSUE TITLE
Feature Request: Draft pull request

### ISSUE THREAD

**Issue by joelbourbon** [Mimeo/VSTSExtension-ActivePullRequests#30]
There is a new feature in VSTS where you can flag a Pull Request as Draft. It is the same as marking a Pull Request title with WIP at the beginning but with this, it actually blocks the pull request in being merged.

Would it be possible to add a little icon or color to identify which PRs are in draft mode?

**Comment by joelbourbon** [comment]
@nshenoy Is this something you would consider doing? If not, do you think it would be a low hanging fruit for me to try and pull request?

**Comment by nshenoy** [comment]
@joelbourbon Go for it! Looks like it might be pretty straightforward. The `pullRequests` API appears to have an `isDraft` property. Example:
```
            "title": "test",
            "description": "test",
            "sourceRefName": "refs/heads/test",
            "targetRefName": "refs/heads/master",
            "mergeStatus": "succeeded",
            "isDraft": true,
```

So I guess the `PullRequest` model in `app.model.ts` should include that property and set it when `getPullRequestData()` is called. Then some sort of decorator could be applied when generating the view in `app.ts`. You might want to look thru their CSS to see if there's some appropriate style that's already there.

**Comment by joelbourbon** [comment]
Hey guys!

I thought about this and I think a better approach would be to filter out the Draft pull requests. I would completely hide them from the list. It would completely de-clutter that UI and would keep on the "Active" pull requests as described by the plugin.

What do you think?

CC: @nshenoy

**Comment by nshenoy** [comment]
@joelbourbon That's a great idea! I like that better. I'll take a look at your PR.

**Comment by nshenoy** [comment]
This has been published to the marketplace. Thanks for the contribution @joelbourbon !

![](https://media.giphy.com/media/3osxYdXvsGw6wT5lIY/giphy.gif)
