### ISSUE TITLE
Feature Request: Display Build Status

### ISSUE THREAD

**Issue by wklaase** [Mimeo/VSTSExtension-ActivePullRequests#35]
It would be nice if you can see the build status of each Active Pull Request (passed, failed, in progress, not run ..), so you can quickly see when the reason that it is not completed is a failed build.

**Comment by xberr** [comment]
Build status and every other Git status as well.

**Comment by sand-head** [comment]
There's a (from what I can tell) undocumented property on builds named `triggerInfo` that contains the PR number if a build is run automatically via pull request, I'm going to try using that to display the most recent build status for a PR. The only issue is that this necessitates a change to this extension's scopes.

**Comment by sand-head** [comment]
added this in #38!

**Comment by wklaase** [comment]
a very nice feature.
thank you so much.
Wouter Klaase

Test Engineer
CGI Nederland.

Op do 6 jun. 2019 om 22:04 schreef Justin S. <notifications@github.com>:
