### ISSUE TITLE
Don't see extension after install

### ISSUE THREAD

**Issue by mattdell** [Mimeo/VSTSExtension-ActivePullRequests#36]
I feel a bit thick here, but I've installed this extension but can't seem to find it anywhere clicking through Azure DevOps.

Where can I find it?

**Comment by nshenoy** [comment]
After the extension is installed for your org, you should see it under the "Repos" group in the navigation pane. Example:

![image](https://user-images.githubusercontent.com/1314114/58999893-1bc29980-87d6-11e9-9da5-bec884777de9.png)
