### ISSUE TITLE
Feature Request: Filter by repositories

### ISSUE THREAD

**Issue by karlingen** [Mimeo/VSTSExtension-ActivePullRequests#43]
It would be nice if we could filter by repository.
Ideally, you'd be presented with a multi-select containing all repositories you have access to.
If the user selects one or more options from the multi-select, the results would be filtered.

A possibility to save the state of the selected values in the multi-select would also be ideal, so that you don't have to reselect those repositories each time you visit the page.

**Comment by nshenoy** [comment]
This feature is live now.
