### ISSUE TITLE
Only 99 pull requests display

### ISSUE THREAD

**Issue by ddemania** [Mimeo/VSTSExtension-ActivePullRequests#46]
Thank you for creating an all active pull request extension.  We have a single large mono-project with many repos, and therefore hundreds of active pull requests.  When using the extension, we only see the 99 most recent active pull requests?  Is this a purposeful limit, or am I missing something?  Maybe a possible solution would be to display a cached 'paged' list of 100, that can be moved through???
![ActivePullRequests](https://user-images.githubusercontent.com/15872279/60300816-6dea6c80-98f5-11e9-888f-62407d72496d.JPG)

**Comment by nshenoy** [comment]
Can we rename this to `99 PRoblems` ? j/k

Looks like the REST API returns a max of 100 PRs and we need to use `$top` and `$skip` to paginate somehow. We'll look into this.

**Comment by JakeRoper4** [comment]
Is there any progress on this? We've just installed this extension in replacement instead of another similar extension, which didn't show all PR's within our system.

**Comment by sand-head** [comment]
I'll see about fixing both this and #66 (and also #73, which I think is related) within the next week

**Comment by sand-head** [comment]
shouldn't have said "fix" and the issue ID like that in the PR. I'm releasing version 1.1.8 now; please let me know if this issue persists.

**Comment by JakeRoper4** [comment]
@sand-head Just had the update on our organisation's Azure DevOps, and it now displaying more than 99 pull requests. Thanks for the great work.

**Comment by sand-head** [comment]
glad to hear it works now! thanks for letting me know and for using our extension!
