### ISSUE TITLE
Refused to display '[PR url]' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by SeanLAllen** [Mimeo/VSTSExtension-ActivePullRequests#48]
After the update to 1.1.0 the PR does not load on the current screen. A sad document appears and says that dev.azure.com refused to connect

**Comment by nshenoy** [comment]
Hard refresh. This is fixed in v1.1.1 of the extension published just now. Sorry about that!
