### ISSUE TITLE
iFrame duplicates sidebar and title bar when clicking into PR

### ISSUE THREAD

**Issue by dizco** [Mimeo/VSTSExtension-ActivePullRequests#49]
Steps:
1. Click on "All Active Pull Request"
2. Click on any open PR
3. Notice the sidebar and the title are duplicated 

See screenshot:
![image](https://user-images.githubusercontent.com/7740408/60829347-b0783880-a182-11e9-9aa4-2735a0bbe990.png)

Version: 1.1.0
Browser: Google Chrome 74.0.3729.169 
OS: Windows 10

**Comment by sand-head** [comment]
this is actually the same bug as #48, which was a bit of an oversight on my part. adding `target="_top"` to the links should fix this issue. if nobody else gets to it in a bit I can submit a PR for this. for now, I recommend middle-clicking. really sorry about this!

**Comment by nshenoy** [comment]
I'll take a look.

**Comment by nshenoy** [comment]
Try now. I just published v1.1.1 with the fix.

**Comment by dizco** [comment]
Thanks for the quick reaction! Seems fixed, feel free to close this issue!
