### ISSUE TITLE
New "My Drafts" tab goes to blank page if clicked too quickly

### ISSUE THREAD

**Issue by joelbourbon** [Mimeo/VSTSExtension-ActivePullRequests#51]
Hey guys!

Thanks for the latest update! It is awesome and beautiful!

One small bug: New "My Drafts" tab goes to blank page if clicked too quickly

Repro steps:
- When in the extension page
- Refresh the page
- Rapidly click on the "My Drafts" tab

Current Result: loads a blank page
Expected Result: Show same skeleton UI than in "Active Pull Requests" tab until loaded

I can take a look if you guys don't have the time 😉

**Comment by sand-head** [comment]
this also seems to happen if you click on the "Active Pull Requests" tab before it's done loading too. may be an error setting a component state somewhere, based off of the React error generated: https://reactjs.org/docs/error-decoder.html/?invariant=185.

sure thing, feel free to look into this further if you want! I'm not sure I'd be able to get to this relatively soon.

**Comment by joelbourbon** [comment]
I feel that it comes from this line: https://github.com/Mimeo/VSTSExtension-ActivePullRequests/blob/master/src/app.tsx#L68

The `state` is binded on `selectedTabId` and is also set in the `onSelectedTabChanged` callback.

I have no way to test this out easily...
