### ISSUE TITLE
Feature Request: Settings Tab to Show/Hide Columns

### ISSUE THREAD

**Issue by kyledodge** [Mimeo/VSTSExtension-ActivePullRequests#56]
Add a new settings tab that will have toggle components to turn on/off each column from being displayed to save screen real estate. It looks like devops extensions can store key value pairs as user settings, so storing a flag for each column as a user preference to show/hide.

Toggle Component: https://developer.microsoft.com/en-us/azure-devops/components/toggle
Extension Data Storage: https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops

It doesn't look like it would take much to do this, I can take a stab at it if it would be merged in

**Comment by nshenoy** [comment]
@kyledodge Go for it!
