### ISSUE TITLE
Extension stopped working after update to 1.1.1

### ISSUE THREAD

**Issue by mkellenbenz** [Mimeo/VSTSExtension-ActivePullRequests#58]
I get the following error in the console:
![image](https://user-images.githubusercontent.com/8045559/61127531-cef67080-a4af-11e9-80a9-7caf1c382477.png)

Request response looks like this:
`{"$id":"1","innerException":null,"message":"HostAuthorizationNotFound","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}`

It's still working for another tenant. I'm in the process of reinstalling the extension. I'll update the issue if I have more infos.

**Comment by mkellenbenz** [comment]
jFYI: A reinstall fixed the issue

**Comment by nshenoy** [comment]
Thanks @mkellenbenz . Sorry for the inconvenience. Just out of curiosity, did you happen to notice if the main page had the "Loading..." message there and the additional message that if it doesn't go away to reinstall? Just wondering.

**Comment by mkellenbenz** [comment]
Hey @nshenoy, we had this issue with the update before 1.1.1 yes. A reinstall as described worked there as well!
