### ISSUE TITLE
"Pending" comments considered resolved

### ISSUE THREAD

**Issue by evandixon** [Mimeo/VSTSExtension-ActivePullRequests#63]
On the Active Pull Requests page, the comments for a PR shows 14/15 comments:
![image](https://user-images.githubusercontent.com/2699524/62866114-ad1e2280-bcd5-11e9-8ec4-8b8bd1ce993c.png)

But clicking on the PR itself shows 12/15 comments:
![image](https://user-images.githubusercontent.com/2699524/62866159-c3c47980-bcd5-11e9-9ee0-6640e3f293e1.png)

This appears to be a matter of "Pending" comments being considered resolved by the Active Pull Requests page, since I currently have 1 active and 2 pending comments.

This appears to be the relevant bit of code: https://github.com/Mimeo/VSTSExtension-ActivePullRequests/blob/ffac59e934ca5b81d4746fc9a51fcb0dcf4f6ec5/src/app.tsx#L156

**Comment by kyledodge** [comment]
Thanks for reporting this @evandixon, I can work on a fix for this tonight

**Comment by sand-head** [comment]
the PR resolving this issue has been merged and the extension has been updated to version 1.1.5. thanks for letting us know @evandixon and thanks a bunch for the quick fix @kyledodge!
