### ISSUE TITLE
Dashboard tile

### ISSUE THREAD

**Issue by AmyAmy** [Mimeo/VSTSExtension-ActivePullRequests#7]
Would be nice to have a (1×1) tile on the dashboard, which shows the number of pull requests. Clicking the tile could navigate to the All Active Pull Requests page.

**Comment by nshenoy** [comment]
Thanks for using the extension! Having a tile is an excellent suggestion. I'll look into it.

**Comment by nshenoy** [comment]
This is a good suggestion, but unfortunately I won't have time to look into this. If anyone wants to figure this out and open a PR, go for it. I'm closing this for now.
