### ISSUE TITLE
Links to PRs wrong for second project

### ISSUE THREAD

**Issue by bender2k14** [Mimeo/VSTSExtension-ActivePullRequests#73]
This extension was working great for us, but recently it stopping correctly.  I think the bug I am about to describe was introduced in version 1.6 on December 18, 2019.

## Steps to reproduce

1. Create an organization in Azure DevOps `MyOrg` called `MyOrg`.
2. Create a project called `ProjectA`.
3. Create a project called `ProjectB`.
4. Create a repository in `ProjectB` called `MyRepo`.
5. Create a PR in `MyRepo`.
6. Navigate to the URL for this extension in `ProjectB`, which is
```
https://myorg.visualstudio.com/ProjectB/_apps/hub/mimeo-vs-marketplace.mimeo-active-pull-requests.active-pull-requests-extension-hub
```

### Actual result

The actual URL for the PR is
```
https://myorg.visualstudio.com/MyOrg/ProjectB/_git/MyRepo/pullRequest/1
```
and no PR data loads (i.e. the menus on top and left load, but the "center" of the screen is just white).

### Expected result

The expected URL for the PR is
```
https://myorg.visualstudio.com/ProjectB/_git/MyRepo/pullRequest/1
```
The difference is that this URL lacks `MyOrg`.  For this URL, all the PR data loads correctly.

### Additional correct URLs

These URLs are not expected but still work correctly.
```
https://dev.azure.com/MyOrg/ProjectB/_git/MyRepo/pullRequest/1
https://myorg.visualstudio.com/ProjectB/ProjectB/_git/MyRepo/pullRequest/1
```

I think the first of those might be the actual URL for version 1.5.

## Same steps for `ProjectA`

When doing steps 4 to 6 for `ProjectA`, the actual URL is
```
https://myorg.visualstudio.com/MyOrg/ProjectA/_git/MyRepo/pullRequest/1
```
and all the PR data loads correctly.

--------

I reviewed the code in an attempt to find when and where this change was introduced.  I think this is the relevant code.
https://github.com/Mimeo/VSTSExtension-ActivePullRequests/blob/68a06e361a122dd9f54b72eb300f861a9a7df58f/src/app.tsx#L164-L170

My best guess would be to set `hostUrl` to `${parentUrl.origin}/${this.projectName}`.  I think that would work for the steps I described above, but I don't know if this would work in all the other current use cases.

**Comment by bender2k14** [comment]
Oh!  I just realized something that was somewhat present in my original comment.

I think the issue stems from the [old and new URLs](https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration):
- Old: `https://myorg.visualstudio.com`
- New: `https://dev.azure.com/MyOrg`

The critical moment in my test above is to click on a PR link after loading the page at _old_ URL
```
https://myorg.visualstudio.com/ProjectB/_apps/hub/mimeo-vs-marketplace.mimeo-active-pull-requests.active-pull-requests-extension-hub
```

If I instead use the _new_ URL...
```
https://dev.azure.com/MyOrg/ProjectB/_apps/hub/mimeo-vs-marketplace.mimeo-active-pull-requests.active-pull-requests-extension-hub
```
...then the PR links work correctly.

Of course this leads to a simple workaround for me: just update the bookmark in my browser to use the new URL.  The only reason I hadn't done this before now was laziness.

I think one way to Implement this in code as _naively_ as possible would be to hard code `parentUrl` to `https://dev.azure.com`.  This works for me.  However, I do think it is unexpected for such a link to point to a different domain.  At least you know from [this comment](https://developercommunity.visualstudio.com/comments/349710/view.html) that the new URL is live for all users.

**Comment by sand-head** [comment]
before that PR I merged last month, our default behavior was to hard-code the URL to `https://dev.azure.com` as you describe. however, as you could see in #66, that unfortunately doesn't work for on-prem users. I think your issue is about line 66 in `/src/app.tsx`, as you point out in your first comment:
```ts
    if (!hostUrl.includes(hostContext.name)) {
```
your `https://myorg.visualstudio.com` URL has the organization in lowercase, but line 66 isn't doing a case-insensitive match for the organization name, hence why it tacks it onto the URL anyways. the easiest fix would be to change it to something like:
```ts
    if (!hostUrl.toLocaleLowerCase().includes(hostContext.name.toLocaleLowerCase())) {
```
if you feel comfortable submitting a PR to make this fix, I can get it merged and pushed out. otherwise, I'll try to get it out with a couple of other fixes soon.

**Comment by sand-head** [comment]
whoops! didn't mean to close. I'm pushing this live in version 1.1.7, which should go out any moment now. let me know if this resolves this issue for you

**Comment by bender2k14** [comment]
> whoops! didn't mean to close.

Oh, sorry.  That was my fault.  If you start a PR description like I did with
> Fixes #73
then completing the PR also closes the referenced issue.

**Comment by bender2k14** [comment]
> let me know if this resolves this issue for you

Yep.  This issue is fixed for me now.

**Comment by sand-head** [comment]
glad to hear! thank you so much for the detailed issue and again for putting the PR out
