### ISSUE TITLE
When 0 Pull Requests, Grid Never Finishes Loading

### ISSUE THREAD

**Issue by kyledodge** [Mimeo/VSTSExtension-ActivePullRequests#77]
Today the extension in DevOps cloud stopped working when there are 0 PRs. I’m guessing this was due to the latest update. The screen just shows the loading image but if you inspect devtools there are hundreds of api calls, each returning an empty result. If we have at least 1 PR the extension works fine.

**Comment by sand-head** [comment]
my bad! I'll push a fix out for this in a bit

**Comment by sand-head** [comment]
pushing the fix out in version 1.1.10 as I type; let me know if you're still encountering this issue and I can reopen it. thanks!

**Comment by kyledodge** [comment]
Looks good now - thanks for the quick fix!
