### ISSUE TITLE
Incorrect Uri for PR on Azure DevOps when organization name ends with project name

### ISSUE THREAD

**Issue by dizco** [Mimeo/VSTSExtension-ActivePullRequests#79]
When clicking on any "Active Pull Request" via the extension page, we get redirected to a 404 page of Azure DevOps.

## Repro steps:
1. Navigate to `https://dev.azure.com/FooBAR/BAR/_apps/hub/mimeo-vs-marketplace.mimeo-active-pull-requests.active-pull-requests-extension-hub`
2. Click on any active PR. We get redirected over to `https://dev.azure.com/FooFooBAR/BAR/_git/myrepo/pullRequest/1`

Notice that `Foo` is there twice. I think this might be caused by #76 since it appeared over the weekend

**Comment by Perfect-Web** [comment]
@dizco yes, it happens to be as well

**Comment by sand-head** [comment]
you're correct, I overlooked this when I made the changes I merged in in #76. I have a new PR out to fix this (and hopefully #66) and I plan on merging it soon, just wanna make sure this definitely works in every scenario I can test before pushing it out. thank you for bringing this to my awareness!

**Comment by sand-head** [comment]
I'm pushing this live in version 1.1.10 now; feel free to reply to this issue if you're still experiencing this issue and I'll reopen it

**Comment by dizco** [comment]
@sand-head thank you, issue is fixed for me!
